PreTeXtBook/pretext

doc/guide/appendices/glossary.xml

Minor edits to Asymptote and PDFLaTeX entries in the glossary.

Update Asymptote and PDFLaTex definitions

---

examples/sample-article/sample-article.xml
xsl/mathbook-html.xsl

I needed a new Javascript version for the new reading questions interface.
Since I was in the neighborhood, I added some index entries to the sample article.

Javascript013

---

xsl/mathbook-html.xsl

For code review and merge if it appears OK.
https://github.com/PreTeXtBook/JS_core/pull/28 will have to be approved before this will actually work.
Taking the opportunity to remove some illegal attributes to the iframe. I see no bad consequences in output.

WeBWorK: randomize inline exercises

---

script/mbx

This might address #1136. I've tested that it does no harm to the common workflow. (On Python 2 and 3, it still makes the WW sample chapter PDF with the image files for me.)
It changes to only use regex to graph the image file path, not to do any further parsing. Further parsing is done by the urllib.parse module and the os.path module, which can be better trusted to work as intended.
@coltongrainger, may I ask you to test this? If I understand correctly, you would return to a situation where you are using a WW server in such a way as to get image URLs like: `http://127.0.0.1:8080/wwtmp/anonymous//gif/df899ba6-b336-33a5-9603-8b672b91ccc7___6bb688ad-bad2-32ef-ad88-fc9d44e14581.png` and see if the image extraction succeeds now.
I recommend not merging this until Colton or someone can test …

WeBWorK: refactor image file extraction

---

pretext/pretext.py

This establishes the WW version and will give helpful error messages.
Try with `SERVER = https://webwork-ptx.aimath.org` and all should go smoothly.
Try with `SERVER = https://www.pcc.edu` and (since there is no WW server there) you will get an error message.
Try with `SERVER = https://secure.willamette.edu` and (since the version is 2.10) you will get an error message that the version is too old.
The real reason I wanted to have this is so that the new json approach to WW exercises can be conditioned on using version 2.16 or above. (Or maybe 2.17 if I'm not quick enough.) I will change the label for the AIM development server to 2.16 to keep going.

WeBWorK: detect server version

---

xsl/pretext-html.xsl

This PR addresses the discussion at https://groups.google.com/d/msg/pretext-dev/38Zgdboa0wM/x9VQm0P7AQAJ.

HTML: classes for interactive exercise wrapping divs

---

doc/guide/publisher/webwork.xml
examples/webwork/Makefile

Following up on this forum thread: https://groups.google.com/g/pretext-support/c/bNBNuEJwEps/m/cMs8-cFwAgAJ

WeBWorK: stress importance of appropriate protocol in documentation

---

doc/guide/publisher/conversions.xml

we just talked about this on zoom!

Guide: describe customizations

---

xsl/localizations/fr-CA.xml
xsl/localizations/fr-FR.xml

I translated the newly added Appendices (plural) to... Appendices and upon researching found out that Listing also translates to Listing.

Additional fr translations

---

doc/guide/author/author-faq.xml

I think we could point to FAQ#1 more often if it were not specific to knowls and sage.

Guide: broaden scope of FAQ#1

---

examples/sample-article/sample-article.xml
xsl/pretext-html.xsl

This addresses an issue that Juan Carlos Bustamante and D Brian Walton unearthed here: https://groups.google.com/g/pretext-support/c/5L_XUwcWzBw/m/EuVniXy0AgAJ

GeoGebra: do the right thing with all whitespace text content

---

xsl/pretext-html.xsl

This won't work until we simultaneously submit a companion pull request to JScore.

WeBWorK: Use iframe for live html

---

examples/webwork/sample-chapter/sample-chapter.xml
pretext/pretext.py
xsl/extract-pg.xsl
xsl/pretext-common.xsl
xsl/pretext-html.xsl
xsl/pretext-latex.xsl

This makes `task` work in a `webwork`. There is also some cleanup of the webwork portion of the pretext script.
No schema changes here. If this is good to merge, I will add `task` (and deprecate `stage`) in a separate PR.

WeBWorK: task

---

doc/guide/author/topics.xml

I read the new table stuff in the guide. It's good. I found a few things to fix. Of the four things here, the latter three I *think* are things to actually fix. The first thing is a little different.

Guide: edits to table description

---

pretext/pretext.py

Script: better error-handling for failed stylesheet processing

---

xsl/localizations/af-ZA.xml
xsl/localizations/bg-BG.xml
xsl/localizations/ca-ES.xml
xsl/localizations/cs-CZ.xml
xsl/localizations/de-DE.xml
xsl/localizations/en-US.xml
xsl/localizations/es-ES.xml
xsl/localizations/fi-FI.xml
xsl/localizations/fr-CA.xml
xsl/localizations/hu-HU.xml
xsl/localizations/it-IT.xml
xsl/localizations/pt-BR.xml
xsl/localizations/pt-PT.xml
xsl/pretext-html.xsl

More localizations for strings that can be button text.

Interactive exercises: more localizations

---

xsl/support/runestone-services.xml

This contains a fix for the race condition in multiple choice questions that use MathJax in the `<choice>`

Update to runestone version 6.3.0

---

doc/guide/author/webwork.xml
doc/guide/publisher/webwork.xml

A little updating of the WW docs.

Guide: update WeBWorK docs

---

doc/guide/author/topics.xml

Here's a small thing for math best practices.

Guide: commas as thousands place separators

---

xsl/extract-pg.xsl

This adds a context to the list of recognized contexts for PG.

WeBWorK: add contextForm.pl to recognized macros

---

xsl/pretext-latex.xsl

LaTeX: empty page style on extra blank pages

---

examples/sample-article/gen/dynamic_subs/dynamic_substitutions.xml
examples/sample-article/sample-article.xml

Restored the two dynamic exercises in sample article and provided the necessary substitution file for the static build to work.

FITB: static substitutions
