PreTeXtBook/pretext

xsl/mathbook-html.xsl
Added the `str` namespace to `html.xsl` in the same way `common.xsl` does this, so that I could use `str:replace` to replace `\pi` with `\(\pi\)`. Now an author is closer to being able to treat the contents of mag in the same way they would treat the argument to `\num{}` or first argument to `\SI{}{}`.
Note: `siunitx` input for these arguments is much more sophisticated. This is still far from what an `siunitx` MathJax extensions would give us.
=> Support for \pi in mag in HTML

doc/author-guide/add-ons.xml
Links in posted HTML author guide were not working. Tracked it to these typos.
=> Fix typos in author guide

xsl/mathbook-html.xsl
Changes to interactive reading questions required incompatible changes to
the Javascript.  Only difference for PreTeXt is changing Javascript version from
0.11 to 0.12.
=> Upgrade Javascript to version 0.12

doc/guide/publisher/pdf-print.xml
The stringparam in xsl/mathbook-latex.xsl that controls sidedness of PDF is "latex-sides".
The documentation in the publisher's guide says "latex-sided". 
The pull request is to make the publisher's guide match the XSL.
=> Correct stringparam name for 1-side vs 2-side

examples/sample-book/frontmatter.xml
In the sample-book, both the `book` and `frontmatter` elements have xml:id "sample-book". I was seeing a duplicate xml:id error. This changes the `frontmatter` id to "frontmatter".
=> Give sample book frontmatter new xml:id

xsl/mathbook-html.xsl
To help develop more HTML styles, now there are separate CSS files for the TOC, banner,
knowls, and the main body style.  This is accompanied to a CSS version change to 0.31
(skipping 0.3 because it was used briefly for development).
=> Separate CSS files and switch to CSS version 0.31

examples/webwork/minimal/mini.xml, examples/webwork/sample-chapter/sample-chapter.xml, script/mbx
This follows through with #873, removing `title` and `idx` as schema-compliant children of a `webwork`. To go along with that, `title`s are removed from the sample-chapter and minimal webwork examples. And lastly, there was a section in the `mbx` script that was intentionally copying authored `title`s into the static representations, and this removes that.
I think I am doing the right thing, in only editing `schema/pretext.xml` in the schema folder. And I think that means you generate the other schema folder files before making the "real" commit for this.
=> WeBWorK: remove title from samples, mbx script

examples/showcase/environments.ptx, examples/showcase/exercises.ptx, examples/showcase/pretext-showcase.ptx
Main commit here adds an exercises section to the Showcase Article. Two other commits clear trailing whitespace and schema violations from the environments section.
The Showcase Article currently has these schema violations, which may just be signs that the schema is ready to catch up:
- It doesn't like `index` having an `introduction`.
- It doesn't recognize `document-id` and `html` from `docinfo`.
- It doesn't recognize `reading-questions`.
- It doesn't recognize `subexercises`.
The latter two are introduced by this PR. Unsure if you'd want to wait to merge this until the schema has some of these things.
=> Showcase exercises

doc/guide/author/webwork.xml, examples/webwork/sample-chapter/sample-chapter.xml, schema/pretext.xml, xsl/extract-pg-common.xsl
Allows a `webwork` to have a `description` element. If the `webwork` is PTX-authored, this goes into a `COMMENT()` in the archival (aka verbose) version of the PG file. (OPL problems tend to have a description like this as perl comments at the top of the file, but we feel that is less useful than in a `COMMENT()`. If there is user feedback, we could duplicate the description in the "traditional" way too.)
If the source is a problem file on the server, nothing is done with any `description`. This seems appropriate, since we assume server problems are managed separately. Anyway it would be unusual for a "webwork" with "@source" to not be a self-closing tag and have child elements. 
I did a file diff on the webwork extraction files, and the only changes are the good ones.
Please take a …
=> WeBWorK: description element

examples/webwork/sample-chapter/sample-chapter.xml, pretext/pretext.py, xsl/extract-pg.xsl
This is mostly as the commit says.
Additionally, there are some conditional checks if the WW version is 2.16 to write an `interactive` element instead of the four `server-url`s. The only "2.16" server is PTX-dev. After this, I'll work on the HTML style sheet so it can actually work with what comes from a 2.16 server.
Also, there will be "stage -> task". To be handled later.
I compared the diff for the representations file before and after. Caught a few things, and on the final run the only diffs were things to expect.
=> WeBWorK: build representations using lxml

examples/webwork/Makefile, examples/webwork/sample-chapter/sample-chapter.xml, pretext/pretext.py, xsl/pretext-html.xsl
This is not ready to merge, but it is ready for some testing and feedback. I'm going to be offline the next few days, and I wanted to get some eyes on this to see what you think. The only testing I did is making the sample chapter HTML with the webwork-ptx server and it seems OK. I didn't check a diff though. And then making the sample chapter HTML with the webwork-dev server and it seems OK too. 
I haven't considered accessibility, but I will before this PR is closed and merged. There needs to be aria-live somewhere.
The Runestone stuff is on, which I think should not be the case for the final PR here. It makes some console errors when the book is not actually in Runestone. I intend for this PR to just be about the static preview -> live WW mode for HTML output. Not anything having to do …
=> WeBWorK: static preview for 2.16+

examples/sample-article/sample-article.xml, xsl/pretext-latex.xsl
This addresses an issue reported in the [forums](https://groups.google.com/d/msg/pretext-support/oxbk1KJ1PxQ/ZY62v2mxCAAJ) where a `sidebyside` that is the first child of a `paragraphs` causes an issue with the title of the paragraphs.
I also took the liberty of moving most instances of `\leavevmode` to the same area. 
The approach I took was to tie the `\leavevmode` to the thing it precedes, not to the parent of that thing, an alternative which was considered. 
Aside from expected diffs (timestamps and different generated id~s) I don't see any diff on the sample article or sample chapter.
=> LaTeX: corral leavevmode and apply to paragraphs/sidebyside

pretext/pretext.py
First commit addresses something @mitchkeller noticed. WW representations build was not closing a file nor the requests session, and that leads to resource usage warnings if python is set to show all such warnings.
Test by changing Makefile from `$(MB)/pretext/pretext -v -c webwork -d $(WWOUT) -s $(SERVER) $(SMPCHP)` to `PYTHONWARNINGS=module $(MB)/pretext/pretext -v -c webwork -d $(WWOUT) -s $(SERVER) $(SMPCHP)`, same for sample chapter. You will see the warnings at the end of reps building, but not after this commit. Output reps file has no meaningful diff.
Second commit is just that I happened to notice sessions being initiated in other subroutines that appear to never be used.
=> Pythonwarning

xsl/pretext-html.xsl, xsl/pretext-latex.xsl
I suspect (but am not sure!) that these are mistakes. Maybe one mistake, then a copy-paste into the other stylesheet.
Of course I am only looking at this as I crib stuff over into the odt stylesheet.
=> Fix plusminus handling

xsl/extract-pg.xsl
APEX had a `...<q><m>\dx</m></q>` where `\dx` is one of Greg's macros (`\Delta x`). What _should_ have been happening is that the `m` receives a `b-human-readable` parameter, and if that is true, it puts the macro definition right there in the PG:
```
..."[`\newcommand{\dx}{\Delta x}\dx`]"
```
But the `q` template from -common was catching this, which does not receive `b-human-readable`, let alone pass it along to the `m`.
So this PR adds a template for `q` (and a few other things) to the extract-pg stylesheet.
=> WeBWorK: tunnel human readability param through groupings

examples/webwork/sample-chapter/sample-chapter.xml, pretext/pretext.py
Prior to this commit, there are situations where WW reps building can fail without a good explanation. The references below to `last[0]` kill python when `last` is an empty list. (Which can happen in silly ways, like literally putting nothing into a `statement`, but also when using an OPL problem that is not PTX compatible.) Now if that happens, you get a warning that something was empty, and processing otherwise proceeds. And I put one triggering example in the sample chapter.
This branch started out as its name implies, to cleanse sidebyside (gracefully) from within a webwork. But one thing leads to another in ways that feel too intertwined to do on separate branches. So I'll try to isolate meaningful changes one commit at a time, and await review and merging. (No rush!)
=> WeBWorK: warn if content is missing

examples/webwork/sample-chapter/sample-chapter.xml
Here's the next one. Trivial, I think. The Sample-chapter had xml:id~s on webwork elements, but we don't allow that. I moved them all to the enveloping exercise.
=> WeBWorK sample chapter: move xml:ids from 'webwork' to 'exercise'

examples/showcase/webwork.ptx, examples/webwork/sample-chapter/sample-chapter.xml
Another trivial one. Titles on some stages (and making them match across the sample chapter and the showcase article) and removing an outdated comment about hints.
The next one will really remove sbs from webwork.
After that, the only thing left maybe controversial: adding the `data` attribute to the schema.
=> WeBWorK sample chapter and showcase article: cleanup

xsl/extract-pg.xsl
I'm not sure why this was here. I think that it was needed at one time, but -common evolved nad now it is resposible for seeing `[NUM]` in output. After removing this, output is good.
=> WeBWorK: fix exercisegroup xrefs

xsl/pretext-html.xsl
This is needed for MathJax3 inside a live WW that comes from a version 2.16 server. It is a configuration option for when math is in a `<script type="math/tex">...</script>` instead of inside `\(...\)`. And this is how WeBWorK delivers math content. With MathJax2, nothing special needed to be done about that, which is why I hadn't noticed it before. It's less because of PTX moving to MathJax3, and more because of WeBWorK doing so recently as well.
If you pull this, then rebuild the sample chapter. I have edited `pretext-webwork.js` (and @davidfarmer, I committed that edit and pushed it to GitHub) such that the math renders on a local build of the sample chapter.
=> WeBWorK: MathJax 3 configuration

doc/guide/author/overview.xml, doc/guide/author/topics.xml, doc/guide/author/webwork.xml, doc/guide/publisher/webwork.xml, examples/webwork/sample-chapter/sample-chapter.xml, pretext/pretext.py, xsl/extract-pg.xsl, xsl/pretext-assembly.xsl
While I was doing the last batch of PGtikz edits, I ran into these small things that I wanted to change. They are small things that didn't really fit into the PGtikz pull request. So I separated them, but I still think they are good changes to assess separately. It may help to look at them one commit at a time.
Why `<webwork/>` in place of `<webwork />`?  It made it a little easier for me to search for the real `<webwork ...>` that are not just generators.
The "description fix" fixes something that is actually broken.
One commit is trivial typo correction for WeBWorK camelcase.
The other two (I believe) give helpful debugging info during image and webwork extraction.
=> Miscellaneous side commits during PGtikz work

pretext/pretext.py
In the URLs that we use to return content from the WW server, this change explicitly asks for solutions and hints to be returned as well. Until recently, they were always returned.
=> WeBWorK: explicitly ask for solutions and hints from server

doc/guide/author/webwork.xml, examples/webwork/sample-chapter/sample-chapter.xml
Not urgent. I realized there is nothing wrong with doing like:
```
\draw (0,0) -- ($a,0);
```
in tikz code in a webwork, instead of having to do:
```
\draw (0,0) -- (<var name="$a"/>,0);
```
Latter is still an option, and it rare cases, may be necessary.
The former is much more pleasant. Such is my experience after an afternoon converting one section of APEX webwork images to tikz.
=> WeBWorK: document simpler vars in tikz

pretext/pretext.py, xsl/extract-pg.xsl
This PR makes it so that when you build the WW representations file from a 2.15 or earlier server, it takes the `pretext/@xml:lang` and uses that in the query string for the iframe src.
To test, put `xml:lang="fr-CA"` on the sample chapter's root `pretext` element. Then change the WW server in the `Makefile` to `webwork-dev.aimath.org` which, for a limited time only, is broadcasting itself as a 2.15 server. Then run `make sample-chapter-representations` and then `make sample-chapter-html`. You should get HTML where the WW are in iframes, and have French buttons. Well, one or two buttons might not be in French, but that is because of the WW localization files for French not being updated.
=> WeBWorK: use language string in server-url for 2.15 and earlier

xsl/extract-pg.xsl
This changes from using `pretext/@xml:lang` to using `$document-language` to address the problem I caused with #1486.
=> WeBWorK: use document-language

xsl/pretext-html.xsl
Before this, try `pretty_print(html("$a^2$"))` in a Sage cell from `section-sage-cells.html` of the sample article. With MJ3, you will see no output. After this, you will see the output math.
With each test, make sure to clear your cache. The MathJax config from a previous run may stick around.
=> Sage: load special MathJax3 findScript config when sage is used

script/mjsre/mj-sre-page.js, script/mjsre/package.json
Incorporates the fix from @dpvc for MathJax 3.2.0 and updates packages.json to current versions.
=> Update mj-sre-page.js to work with MathJax 3.2.0

pretext/pretext
I included "from the command line" in the file-does-not-exist warning message for `file_type == 'config'` (even though files for both `file_type == 'source'` and `file_type == 'publisher'`  also come from the command line but don't include that extra bit in their logging messages) because the most likely name for a user-supplied config file is `pretext.cfg`. So a warning message that just says "executables configuration file pretext.cfg does not exist" would be ambiguous without the "from the command line" part because there are two other pretext.cfg files it could be talking about: pretext/pretext.cfg and user/pretext.cfg from the mathbook path.
=> Script: verify existence of command-line-supplied config file

xsl/extract-pg.xsl
Suppose you have a webwork with tasks 1 and 2. When the problem is made interactive, task 1 is open and task 2 is collapsed and you may not open it.
Previously, when you correctly answer task 1, then of course task 2 opens. But task 1 will collapse. (You can open it back up by clicking on it.)
This change leaves task 1 open when you move on to task 2. I think this is better behavior for live problems in a PreTeXt book. The user can collapse task 1 if they want to.
To see before and after, try the sample chapter problem here:
Exercise 2.2: Solving Quadratic Equations 
https://pretextbook.org/examples/webwork/sample-chapter/html/section-2.html#quadratic-equation
And then after this commit, you should see the behavior described above.
=> WeBWorK: leave open correct scaffold sections

xsl/pretext-common.xsl
Before this, when a warning message is issued and it has line break characters, you get like this:
```
*  ********************************************************************************
*  EPUB conversion is experimental and not supported.  In particular,
creating an EPUB requires the pretext/pretext script.
*  ********************************************************************************
```
With this in place, you get:
```
*  ********************************************************************************
*  EPUB conversion is experimental and not supported.  In particular,
*  creating an EPUB requires the pretext/pretext script.
*  ********************************************************************************
```
I only applied it to this EPUB message. Not sure if warnings with …
=> Common: utility template to print warning messages one line at a time

xsl/pretext-epub.xsl
This deals with the issue of authors putting things into a PTX title that are fine inside an XHTML `hn` but not allowed inside an XHTML `head/title`. Since the `head/title` is not reveled by any reading systems, we simply put in a PTX-generated identifying string that we know won't contain any other XHTML tags. (For example, this now renders something like "Section 3.2.1" or "Conclusion".)
=> EPUB: Simplify what is written into the XHTML head/title

xsl/pretext-html.xsl
Work on hN revealed what I think is a mistake, fixed here.
See 
Exercise 4.10: A very structured exercise 
https://pretextbook.org/examples/sample-article/html/interesting-corollary.html#exercise-structured
Inspect the HTML and note that task (a) has two h6 elements. One for "(a)" and one for the title. This PR merges them into one.
The same issue is present in the solutions at
https://pretextbook.org/examples/sample-article/html/solutions-backmatter.html
So there is an addition here that adds the title to the right h6. And then two removals, removing the other title where born and when part of a solutions.
=> HTML: merge task headers

xsl/pretext-common.xsl, xsl/pretext-html.xsl, xsl/pretext-latex.xsl
This is an alternative to #1572. In this branch, where an exercisegroup is born, either its authored title is printed, or if there is no authored title, the default tile ("Exercise Group", localized) is used.
Some screenshots of a local project. PDF:
HTML:
=> Give exercisegroup a default title

xsl/pretext-html.xsl
As discussed at https://groups.google.com/g/pretext-dev/c/5uscyWjQ0cU/m/LX4uHU_dAAAJ, this changes the "headings" for structural divisions inside a "solutions" to use `span` instead of `hN`.
Actually it makes the `mode="html-heading"` template handle the situation when no `$heading-level` is passed to output a `span`. In case there are more situations where a "heading" should be a decorative span instead of a functional hN, this will help.
=> HTML: in solutions and list-of, make a structural heading use span instead of hN

xsl/pretext-latex.xsl
Replacing #1593.
In one project, I have a terminal task with `@workspace` and the task ends with a `sidebyside`. This causes a `\\` following the sidebyside to give a "no line to end" error. So this PR replaces the `\\` with a paragraph break.
I think this section (workspace on tasks) is "rough" as already noted in the comments. But changing to `\par` seems good for now.
=> LaTeX: par break before workspace

xsl/pretext-common.xsl, xsl/pretext-html.xsl
This returns to using hN (at the appropriate level) for headings in `list-of` and `solutions`. A chunk level 0 example is here:
http://spot.pcc.edu/~ajordan/temp/derivatives.html
(Don't click to follow links to appendices the nav column. They incorrectly point to backmatter.html which should not exist with chunk level 0.)
If you use Firefox and haven't already, I like the [headingsMap extension](https://addons.mozilla.org/en-US/firefox/addon/headingsmap/) to view the headings and their depths in a side column.
There are `solutions` in 4.2.7, and in appendices B–E.  Appendices F and G have `list-of`.
This is the same as where PR #1582 wound up, but there were too many course corrections there and the thread was confusing.
This undoes something that #1580 did, but leaves in place the …
=> HTML: use hN for duplicate headings

doc/guide/author/webwork.xml, doc/guide/basics/basics-part.xml, examples/sample-article/sample-article.xml
I think I keep being led to write like `<attr>key=value</attr>` because I look up other instances and see it there, and think it is an OK thing to do. So this commit removes those instances.
=> Doc: clean up incorrect use of 'attr'

pretext/pretext.py
When sending a request to the WW server, there is parameter `&problemUUID` that we have not used up to now. It did not exist when we first started WW-PTX, and I've been slow to come back to using it. This PR uses it, using the PTX visible-id of the problem.
I recently discovered that this is really needed. Take a look at:
https://pretextbook.org/examples/webwork/sample-chapter/html/section-9.html
Open checkpoint 9.1 and you will see the wrong graph. It's a graph of a cubic function that belongs in checkpoint 9.3. The explanation is that not using `problemUUID`, image files are overwriting each other on the server. Caching of image files with the same name compounds the issue, so even if you make that problem live, you still may see the wrong graph. But with `problemUUID` in use, `make …
=> WeBWorK: use the problem id as problemUUID

xsl/entities.ent, xsl/pretext-common.xsl, xsl/pretext-html.xsl
This puts the appropriate heading level on all of the hN for block objects in HTML. It's all controlled by the modal `hN` template which essentially counts ancestors that would appear on the page with a heading already.
Things I've tested:
- A diff on the before/after HTML output only has good changes. That diff is a monster, so if you want to look at it too, I pre-processed the files before making the diff. I changed `h\d` to `hN` so it wouldn't show lines where only the N changed.
- As noted in a thread, in the knowl files, an svg namespace is either moved or dropped altogether. Seems harmless.
- I inspected the headings all the way through the sample article HTML output, both at chunk level 0 and chunk level 1. The heading tree tool shows no invalid heading depth jumps. And I manually …
=> HTML: straighten out heading level for block elements

doc/guide/author/overview.xml, doc/guide/author/topics.xml, doc/guide/basics/basics-part.xml
A few items added to documentation:
-the `paragraphs` element
-more details about multiline math
-how to break long titles into lines
=> Guide: multiline math, paragraphs, long titles

.gitignore, examples/humanities/codechat_config.yaml, examples/minimal/codechat_config.yaml, examples/sample-book/codechat_config.yaml
This PR adds CodeChat project configuration files for three of the example books:
- `examples/minimal` and `examples/humanities`, both using the PreTeXt CLI.
- `examples/sample-book`, using the PreTeXt script. It assumes that `python3` will execute a Python interpreter where all the necessary libraries are installed (lxml, etc.). If PreTeXt is installed in a venv, perform the following edit to `examples/sample-book/codechat_config.yaml`:
Change line 37, which is:
`args: python3 ../../pretext/pretext --component all --format html --directory {output_path} sample-book.xml`
to (for Linux/OS X):
`args: C:/path/to/venv/bin/python ../../pretext/pretext --component all --format html --directory {output_path} sample-book.xml`
or (for Windows):
`args: /path/to/venv/Scripts/python …
=> Add CodeChat project configuration files

examples/sample-article/sample-article.xml, xsl/pretext-html.xsl, xsl/pretext-latex.xsl
Within `<biblio type="bibtex">` there are new tags available, sufficient for
bibliography entries in a typical math paper.  It is expected that all content is
tagged, with no text elements.  Output preserves the order of the tags in the
source.
Examples added to the sample article.  Tested in HTML and LaTeX.
Update to the schema will be submitted in an issue.
=> Bibtex-style bibliography entries

xsl/pretext-html.xsl
In a stacked heading, we were wrapping each line with a `p`. The intent was to give a screen readers a clear signal to pause between lines. But that makes invalid HTML and invalid EPUB. This removes the `p` and drops a `br` where needed instead.
=> HTML: replace p with br for stacked headings

pretext/pretext.py
This does two things.
1. Put authors on their own line on LaTeX-based cover image. This will make it much less likely that names run off into the margin.
2. Remove the page number "1" that was previously appearing on this cover page image.
=> EPUB: put authors on their own line on LaTeX-based cover image

pretext/pretext, pretext/pretext.py
This addresses #1687. Perhaps inefficiently, but it works.
=> Script: 'all' format option for generated Asymptote images

xsl/pretext-latex.xsl
Following from discussion at #1710, this is a smaller change such that fillin can now only compress down to 80% of intended width.
Later #1710 will be replaced with something that is a more significant overhaul that I have on a local branch.
=> LaTeX: make fillin only contract up to 20%

doc/guide/publisher/publication-file.xml
The section of the Guide on using the publication file to control exercise component visibility has a bit of a contradictory statement regarding using `project` or `exercise-project` as the element name in the publication file. Just using `project` as the tabular calls for at present results in `exploration` not hiding all the things that are set to `no`, even though `project` appears to do what is expected. By using `exercise-project` in the publication file, this behavior is unified across `project` and `exploration`. It's possible that this PR is in error and something should be changed in the processing of the publication file, but this seems to get things into the state that is described before the tabular.
=> Guide: Correct publication file element name for project component visibility

examples/sample-article/sample-article.xml, xsl/pretext-latex.xsl
I'm making dinner too :)
This is only tested on the sample book. But works for all three fillin text styles as far as my eyes could catch.
Haven't tested against Mitch's issue when the fillin is at the start of a new line. I'll need to fiddle up an example to test that.
=> LaTeX: make \fillin behave at start of paragraph

schema/pretext-validation-plus.xsl
One thing got through that should have been in #1783. Removing this (now unnecessary) thing from validation-plus.
=> WeBWorK: remove PGtikz instance from validation-plus

xsl/pretext-html.xsl, xsl/pretext-latex.xsl
A "note" is for a note about a reference.
This adds "pubnote" for a note about publication information.
=> Use pubnote for publication note in bibliography

xsl/pretext-assembly.xsl
This addresses the issue reported here:
https://groups.google.com/g/pretext-dev/c/taENGzE4wIw/m/hn4WGkGbCAAJ
=> WeBWorK: don't mark webwork tasks as fillin-basic

examples/sample-article/sample-article.xml, xsl/pretext-latex.xsl
First commit here adds tables to the sample article with header cells that have multiple line. LaTeX output does not boldface such content. (Discovered while working on a project where a multiline column header would be good to use.)
Second commit changes -latex to use \bfseries around such cells. Sample article output looks good.
There is a comment in the current -latex:
```
```
I'm unsure how to provoke how it might not be effective. But it may be that this comment is wrt trying to use a boldface command within the `\tablecelllines` argument. But the approach I've used puts the boldface command around the whole `\tablecelllines` macro.
=> Latex multiline headers

examples/sample-article/sample-article.xml
Made a note in sample article that Geogebra interactives written from scratch should use the perspective attribute for setup rather than a scripted setPerspective command.
=> Sample article: comment about Geogebra perspective

pretext/pretext.py
This addresses an issue that came up in the forums:
https://groups.google.com/g/pretext-dev/c/iFtAArtgupU/m/ci5Yd5SlBQAJ
=> WeBWorK: always store image paths using posix filepaths

xsl/pretext-html.xsl
Added classes in all places where previously the CSS was using an id selector.
The new CSS is live.
Did not remove any HTML ids.  Some are not necessary, but some are, so I thought
it best to just leave them as-is.
Built a document and it looked fine.  It is possible that I missed something, but that
can be sorted once people build from the new version.
Note that this change required incrementing the CSS and JS versions
(done as a separate commit).
This replaces pull request #1956
=> No ids in css

doc/guide/preface.xml
`<m>\LaTeX</m>` causes a compilation error using TeX Live 2023.66984.
=> Guide: use latex generator in the preface

xsl/pretext-html.xsl
CSS to 0.81 and JS to 0.31 .
The CSS and JS files are in place.  There were several changes, so it may be
helpful to have a beta for testing before going into general use.
=> HTML: increment CSS and JS versions

js/pretext-webwork/2.19/pretext-webwork.js
This was a mistake in the 2.19 WW js I recently added. I thought I was being clever and efficient by doing a certain thing outside of a loop. But it turns out that caused all hints and solutions for a multi-task exercise to be placed wherever the first hint/solution was. So for example, causing the second task's solution to appear within the first task, after the first task's solution.
This fixes that.
=> WeBWorK: don't put all solutions and hints in the first task

examples/sample-article/sample-article.xml, xsl/pretext-latex.xsl
`pretext-latex.xsl` currently only defines the length `\workspacestrutwidth` when the file contains `exercise[@workspace]`. To support `@workspace` living on other possible `worksheet` descendants, this changes to define the length any time `@workspace` occurs in the document. Two rudimentary worksheets are added to the sample article: one with two `activity` elements each with `@workspace` and one where `@workspace` only appears on `activity/task`.
=> @workspace fix

xsl/pretext-latex.xsl
A relatively recent fix to the latex tcb styles included a missing "app" on line 3332 of `pretext-latex.xsl` which results in the title of an example-like not appearing in pdfs.
Will close #2248
=> Fix typo resulting in missing example titles
